In [3]:
from module import StudentEnrollement as SE


In [2]:
greeting('Khan')

Welcome Khan


In [74]:
s1 = SE(1, 10, 2, 2023)

In [75]:
s1.signUp()

Enter your name: kha
Enter your father name: khan
Enter your email: khan@email.com
Enter your location: mardan
Invalid location


In [68]:
class Person:
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender
        
    def displayInfo(self):
        return f'{self.name}, {self.age} years old, {self.gender}'
        
class Teacher(Person):
    def __init__(self, name, age, gender, subjetTeaches):
        super().__init__(name, age, gender)
        self.subjectTeaches = subjetTeaches
        
    def teach(self):
        return f'{self.name} teaches {self.subjectTeaches}'
    
class Student(Person):
    def __init__(self, name, age, gender, dept):
        super().__init__(name, age, gender)
        self.department = dept
        
    def study(self):
        return f'{self.name} studies in {self.department} dept.'

In [60]:
# p1 = Person('Ali', 18, 'Male')
# p2 = Person('Lena', 29, 'Female')

In [61]:
# p1.DisplayInfo()

In [62]:
# p2.DisplayInfo()

In [63]:
p3 = Person('Ali', '20', 'Male')
p3.displayInfo()

'Ali, 20 years old, Male'

In [64]:
p3.teach()

AttributeError: 'Person' object has no attribute 'teach'

In [65]:
t1 = Teacher('Aslam', 40, 'Male', 'python')

In [66]:
t1.teach()

'Aslam teaches python'

In [67]:
t1.displayInfo()

'Aslam, 40 years old, Male'

In [69]:
s1 = Student('Kamal', 20, 'Male', 'CS')

In [72]:
print(s1.study())
a = 10

Kamal studies in CS dept.


In [79]:
'2/3'+' 5/3'

'2/3 5/3'

In [12]:
from math import gcd
class Fraction:
    def __init__(self, numerator, denomerator):
        self.numerator = numerator
        self.denomerator = denomerator
        if self.denomerator == 0:
            raise ValueError ('Denomerator can not be zero')
        common = gcd(self.numerator, self.denomerator)
        self.numerator = self.numerator // common
        self.denomerator = self.denomerator // common
    def __str__(self):
        return f'{self.numerator}/{self.denomerator}'    
    def __add__(self, other):
        newNomerator = self.numerator * other.denomerator + self.denomerator * other.numerator
        newDenomerator = self.denomerator * other.denomerator
        return f'{newNomerator}/{newDenomerator}'
    def __sub__(self, other):
        newNomerator = self.numerator * other.denomerator - self.denomerator * other.numerator
        newDenomerator = self.denomerator * other.denomerator
        return f'{newNomerator}/{newDenomerator}'
    def __mul__(self, other):
        pass
    def __truediv__(self, other):
        pass

In [13]:
frac1 = Fraction(2,4)
frac2 = Fraction(2,4)
print(str(frac1))
print(str(frac2))

1/2
1/2


In [14]:
result = frac1 + frac2
str(result)

'4/4'

In [102]:
result = frac1 - frac2
str(result)

'1/10'

In [107]:
print(type(frac1))

<class '__main__.Fraction'>


In [5]:
import numpy as np

In [110]:
ar1 = np.array([1,2,3,4,5])

In [113]:
ar1
print(type(ar1))

<class 'numpy.ndarray'>


In [115]:
data = [10,11,12,13]
print(type(data))
ar2 = np.array(data)
print(type(ar2))
ar2

<class 'list'>
<class 'numpy.ndarray'>


array([10, 11, 12, 13])

In [116]:
ar3 = np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
ar4 = np.linspace(0,10,10)
ar4

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [120]:
data = [[12,14,16,18],
       [22,24,26,28]
       ]

In [121]:
ar2d = np.array(data)

In [122]:
ar2d

array([[12, 14, 16, 18],
       [22, 24, 26, 28]])

In [9]:
arzeros = np.zeros((10,10), dtype=np.uint16)
arzeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint16)

In [10]:
arzeros.dtype

dtype('uint16')

In [11]:
type(arzeros)

numpy.ndarray