In [15]:
#terminal command: pip install numpy
# notebook command: !pip install numpy

In [22]:
import numpy as np
#named import 

In [21]:
#numpy stands: numerical python
# num ds: ndarray --> [[1.0,2.0,]]

0.8939966636005579

In [24]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [27]:
data = [10.,20,25,14]
print(type(data))
dataArr = np.array(data, dtype='uint16')
print(dataArr, type(dataArr), dataArr.dtype)

<class 'list'>
[10 20 25 14] <class 'numpy.ndarray'> int8


In [28]:
data = [10.,20,25,14]
print(type(data))
dataArr = np.array(data, dtype=np.float16)
print(dataArr, type(dataArr), dataArr.dtype)

<class 'list'>
[10. 20. 25. 14.] <class 'numpy.ndarray'> float16


In [29]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [11,12,13]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13]])

In [30]:
arr2d.ndim

2

In [31]:
#data = [x,y,z]
data =[[10,20,30], #x=10,20,30
       [100,200,300], #y=100,200,300
       [1000,2000,3000]] #z=100,200,300

dataArr = np.array(data)

In [33]:
dataArr.dtype

dtype('int32')

In [34]:
type(dataArr)

numpy.ndarray

In [35]:
ar1d = np.arange(100)
ar1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
ar1d = np.linspace(10, 50, 5).astype('int8')
ar1d

array([10, 20, 30, 40, 50], dtype=int8)

In [42]:
ar2d = np.ones((3,3))
ar2d.dtype

dtype('float64')

In [53]:
ar2d = np.ones((3,3), dtype='float32')
ar2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [58]:
zeros = np.zeros((5,3,3))
zeros.ndim

3

In [60]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
diagonal = np.diag([1,2,3])

In [64]:
diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [66]:
arr = np.random.rand(3,3)
arr

array([[0.26120441, 0.1660883 , 0.47312276],
       [0.66846131, 0.4659206 , 0.50451359],
       [0.65326601, 0.58429572, 0.45646171]])

In [76]:
ar1d = np.arange(0,10).reshape(2,5).astype('int32')*2
print(ar1d)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [77]:
print(ar1d)
ar1dF = ar1d.flatten()
ar1dF

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
print(ar1d)
ar1dF = ar1d.ravel()
ar1dF

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [111]:
np.random.seed(45)
ourArray = np.random.rand(3,3)
ourArray

array([[0.98901151, 0.54954473, 0.2814473 ],
       [0.07728957, 0.4444695 , 0.47280797],
       [0.048522  , 0.16332445, 0.11595071]])

In [125]:
ourArray = np.arange(1,10).reshape(3,3)
ourArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
ourArray.shape

(3, 3)

In [129]:
shape = ourArray.shape
ourArray.shape[1]

3

In [131]:
ourArray.size

9

In [136]:
ar1 = np.arange(1,10).reshape(3,3)
ar2 = np.arange(21,30).reshape(3,3)
result = ar1+ar2
result2 = np.add(ar1, ar2)
print(f'ar1:\n {ar1}\n ar2: \n {ar2}\n ar1+ar2:\n {result} result2: \n {result2}')

ar1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 ar2: 
 [[21 22 23]
 [24 25 26]
 [27 28 29]]
 ar1+ar2:
 [[22 24 26]
 [28 30 32]
 [34 36 38]] result2: 
 [[22 24 26]
 [28 30 32]
 [34 36 38]]


In [138]:
resultM = ar1*ar2
mResult = ar1 @ ar2
print(resultM)
print(mResult)

[[ 21  44  69]
 [ 96 125 156]
 [189 224 261]]
[[150 156 162]
 [366 381 396]
 [582 606 630]]


In [141]:
#indexing
"""
1.integer
2. boolean
3. fancy
"""


'\n1.integer\n2. boolean\n3. fancy\n'

In [144]:
ar = np.arange(100).reshape(10,10)
print(ar)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [148]:
ar[0:4, 4:7] #row, col

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [172]:
ar = np.zeros((5,3,3,2,3,4), dtype='int32')
r = (np.random.rand(5,3,3,2,3,4)*100).astype('int32')
ar = ar+r
ar

array([[[[[[31, 35,  9, 98],
           [16, 93, 44, 30],
           [54, 74, 54, 51]],

          [[97, 31, 12, 80],
           [87, 58, 98, 53],
           [35,  3, 90, 97]]],


         [[[41, 76, 27, 93],
           [ 5,  3, 10, 58],
           [88, 15, 43, 99]],

          [[38, 87, 68, 63],
           [65, 95, 89, 62],
           [84, 47, 54, 86]]],


         [[[79, 40, 30, 18],
           [35, 19, 64, 80],
           [93, 67, 40, 79]],

          [[82, 80, 34, 99],
           [ 8, 40, 37, 36],
           [95, 73, 83, 25]]]],



        [[[[92,  2, 72, 56],
           [87, 36, 72, 26],
           [97, 67, 85, 52]],

          [[38, 50, 73, 76],
           [40, 33, 77, 81],
           [ 3, 25, 59, 62]]],


         [[[23, 50, 28,  5],
           [77, 50, 19, 95],
           [72, 26, 45, 64]],

          [[81, 28, 42, 84],
           [17, 53, 25, 81],
           [ 2, 60, 30, 84]]],


         [[[47,  9, 44, 86],
           [56, 68,  8, 16],
           [95, 86, 39,  2]],

         

In [161]:
ar[:, 1,1]

array([23, 57,  3])

In [162]:
ar[1,1:, -1]

array([ 4, 22])

In [164]:
mask = ar>50
# mask

In [165]:
ar[mask]

array([68, 60, 73, 98, 84, 72, 66, 52, 57, 57, 99, 96])

In [166]:
ar[ar>20]

array([68, 60, 73, 23, 98, 84, 43, 72, 66, 52, 29, 57, 57, 45, 99, 22, 47,
       96, 40, 37])

In [167]:
rowv = np.array([1,2,3])
colv = np.array([[10], [20], [30]])
rowv, colv

(array([1, 2, 3]),
 array([[10],
        [20],
        [30]]))

In [168]:
rowv+colv

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [169]:
ar = np.arange(15).reshape(3,5)
ar2 = np.arange(8).reshape(2,4)


ValueError: operands could not be broadcast together with shapes (3,5) (2,4) 

In [170]:
#np.where,np.pad, correlate, convolve,unique, argmax, sig
ar = np.arange(25).reshape(5,5)
np.resize(ar, (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])