In [3]:
!pip install numpy
    

In [4]:
#numpy stands for numerical python
# num data structure : ndarray --> [1,2,3]





In [5]:
import numpy as np


In [6]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.dtype)

# within perenthesis , we have the type is <class 'numpy.ndarray'>
# within square brackets , we have the type is int32

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32


In [7]:
# single dimension 

data = [10,20,30,40]
print(type(data))
dataArr = np.array(data)
print(dataArr , type (dataArr), dataArr.dtype)

<class 'list'>
[10 20 30 40] <class 'numpy.ndarray'> int32


In [8]:
data = [10,20,30,40]
print(type(data))
dataArr = np.array(data, dtype = np.float16)
print(dataArr , type (dataArr), dataArr.dtype)

<class 'list'>
[10. 20. 30. 40.] <class 'numpy.ndarray'> float16


In [9]:
# double dimension

arr2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9] 
                ])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# wanna see , how many diemensions?
arr2.ndim

2

In [11]:
data = [[12,34,56],
        [11,35,57],
        [55,77,99] ] 
# x = [ 12,34,56] , y = [11,35,57] , z = 55,77,99

data # single dimension

print(np.array(data))  #converted to 2 dimensions


[[12 34 56]
 [11 35 57]
 [55 77 99]]


In [12]:
# built-in functions 
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
ar1d = np . linspace(10, 60 ,5)
ar1d

array([10. , 22.5, 35. , 47.5, 60. ])

In [14]:
ar2d = np . ones((3,3) , dtype ='float16')
ar2d
# and dtype is   , dtype means , data type object
# print(ar2d.dtype)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [15]:
# three dimensions 

In [16]:
arr3d  = np.zeros((6,3,3))

In [17]:
arr3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
#identity 
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# diaganol
diagonal  = np. diag([1,2,3]) 
diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
# random values will be for 2 dimensions

random = np.random.rand(3,3)
random

array([[0.53687688, 0.54795725, 0.74777895],
       [0.63918147, 0.21986149, 0.09763711],
       [0.82313029, 0.6902674 , 0.92956281]])

In [21]:
ar1d = np.arange(0,10).reshape(2,5).astype('int32')*2
print(ar1d)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [22]:
arr1d = np.arange(100)

In [23]:
print(arr1d)

# wanna convert 1 into 2 dimension
ar2d = np.arange(0,100).reshape(10,10)
ar2d

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
# wanna convert 2 into 1 dimension
twoDim=np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]) 
ar1df = twoDim.flatten()
ar1df

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
# convert 2 into 1

ar1dF = ar1d.ravel()
ar1dF

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.random.seed(45)
ourArray = np.random.rand(2,2)*100
ourArray


array([[98.90115135, 54.95447268],
       [28.1447302 ,  7.72895661]])

In [32]:
ourArr = np.arange(1,10).reshape(3,3)
ourArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ourArr.shape

(3, 3)

In [38]:
shape = ourArray.shape
ourArr.shape[1]

3

In [39]:
ourArr.size

9

In [44]:
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.arange(90,99).reshape(3,3)
result = arr1+arr2
result2 = np.add(arr1,arr2)
print(f'ar1:\n {arr1}\n ar2: \n {arr2}\n ar1+ar2:\n {result} \n result2: \n {result2}\n')

ar1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
 ar2: 
 [[90 91 92]
 [93 94 95]
 [96 97 98]]
 ar1+ar2:
 [[ 90  92  94]
 [ 96  98 100]
 [102 104 106]] 
 result2: 
 [[ 90  92  94]
 [ 96  98 100]
 [102 104 106]]



In [47]:
print(arr1)
print(arr2,"\n")

resultM = arr1*arr2
mResult = arr1 @ arr2
print(resultM) #number wise multiply
print(mResult) #matrix wise 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[90 91 92]
 [93 94 95]
 [96 97 98]] 

[[  0  91 184]
 [279 376 475]
 [576 679 784]]
[[ 285  288  291]
 [1122 1134 1146]
 [1959 1980 2001]]


In [3]:
import numpy as np

In [5]:
ar = np.arange(100).reshape(10,10)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
ar[3:7,5:9]

array([[35, 36, 37, 38],
       [45, 46, 47, 48],
       [55, 56, 57, 58],
       [65, 66, 67, 68]])

In [23]:
arr = np.zeros((5,3,3,2,3,4), dtype='int32')
r = (np.random.rand(5,3,3,2,3,4)*100).astype('int32')
ar = ar+r
ar

array([[[[[[524, 498, 488, 678],
           [621, 426, 396, 551],
           [546, 661, 728, 383]],

          [[464, 641, 542, 596],
           [470, 623, 699, 548],
           [500, 533, 559, 460]]],


         [[[547, 506, 562, 616],
           [573, 475, 577, 670],
           [636, 579, 431, 369]],

          [[537, 602, 457, 643],
           [492, 308, 566, 723],
           [488, 518, 762, 503]]],


         [[[597, 297, 705, 595],
           [658, 633, 763, 461],
           [503, 395, 425, 497]],

          [[483, 638, 654, 501],
           [412, 451, 373, 447],
           [515, 512, 672, 568]]]],



        [[[[460, 597, 482, 559],
           [546, 601, 665, 752],
           [560, 723, 667, 550]],

          [[599, 533, 698, 795],
           [517, 488, 483, 562],
           [586, 616, 307, 662]]],


         [[[473, 390, 642, 803],
           [511, 464, 300, 432],
           [528, 588, 420, 572]],

          [[499, 688, 546, 405],
           [457, 598, 590, 538],
           [630