In [2]:
# single indexing and one dimension
import numpy as np
SIndex =np.array( [1,2,3,4,5])

print(SIndex[2])
print(SIndex[3])
print(SIndex[0])

# slicing indexing 

print(SIndex[0:])
print(SIndex[2:-1])

3
4
1
[1 2 3 4 5]
[3 4]


In [5]:
# move to multidimensions
Dindex = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Dindex)

print(Dindex[0,1])
print(Dindex[2,1])

print(Dindex[0:2,1])
print(Dindex[0:2,1:-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
8
[2 5]
[[2]
 [5]]


In [15]:
# boolean indexing 

boolIndex = np.arange(100)
boolIndex

new = boolIndex>2
print(new)
#  will give us only treu and false

new = boolIndex>2
print(boolIndex[new])

#  will give us numbers , when the is greater...


[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


In [1]:
#fancy indexing 
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

indices = [1, 3, 4]
print(arr[indices])  # Output: [20, 40, 50]

arr = np.arange(0,100,10)

fancy = [1,3,5,7,4,9]
print(arr[fancy],"\n")

# let's try for double for two dimensions

double = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,150,160]])
# double
rows = np.array([0, 1, 2])
cols = np.array([1, 2, 0])

print(double[rows, cols])


[20 40 50]
[10 30 50 70 40 90] 

[20 70 90]


In [ ]:
# Integer Array Indexing for Multidimensional Arrays:


import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rows = np.array([0, 1, 2])
cols = np.array([1, 2, 0])

print(arr_2d[rows, cols])
# Output: [2 6 7]